
# .travis.yml
language: minimal


# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
